### PR TITLE
Table fix for github

### PR DESCRIPTION
**Pull request by poohsen**
each opening <div>---</div> line before a table needs an additional newline on github recently, and for the PDF we need to remove that additional newline again. This commit does that

### CODE REVIEW

**Comment by RobertdeLeeuw-IHomer** [comment]
I had hoped to look into this this week, but cannot get the pdf build to work on my laptop. I normally build the OCPI spec on my desktop. So will try again when I'm back home.

**Comment by RobertdeLeeuw-IHomer** [comment]
I tried generating the PDF from this branch... tables not working. (see attachement)
Dit you try to generate the PDF yourself? Did it work?

[OCPI_2.1-table.pdf](https://github.com/ocpi/ocpi/files/947495/OCPI_2.1-table.pdf)

**Comment by poohsen** [comment]
yes, it worked. Are you sure you're following the procedure layed out in `how_to_make_a_new_release.md` ? It's not exactly the most streamlined process so it can be a source of confusion. Since you're the main maintainer as of now you should probably adapt it to what works best from your POV.

**Comment by RobertdeLeeuw-IHomer** [comment]
I have build the spec before, I can build the master and current bug-fix branch without any problems, tables are working. But as you can see in the attached pdf above, the tables do not work in this branch. I hope to find some spare time soon to look into the details and markdown source that is required by GitHub & pandoc to make them both work.

**Comment by poohsen** [comment]
can you post your `all.md` made from this PR please?

**Comment by RobertdeLeeuw-IHomer** [comment]
Hereby my all.md (by the way I had to zip it.)
[all.md.zip](https://github.com/ocpi/ocpi/files/952359/all.md.zip)

**Comment by poohsen** [comment]
the regexes in make_pdf.sh were not compatible with your cygwin setup, which results in a `all.md` that mixes UNIX and DOS-style line endings. I pushed a fix to `make_pdf.sh` just now. Please try again.

**Comment by RobertdeLeeuw-IHomer** [comment]
I was making the same fixes. Als add a small fix. Now it work correctly.

**Comment by simonschllng** [comment]
If you use this fix, we can delete the other one, right? https://github.com/ocpi/ocpi/tree/fix-md-tables
I found it much easier without those html-div-comments...

**Comment by RobertdeLeeuw-IHomer** [comment]
Sorry didn't look at your solutions. If it does not contain any other changes it can be removed.

**Pull request merged**
