### PR TITLE
bugfix markdown tables locations.md

### PR DESCRIPTION
**Pull request by estation**
Tables are not displayed correctly at the moment, because of  \<div\> elements in the .md files.

### CODE REVIEW

**Comment by RobertdeLeeuw-IHomer** [comment]
I will have a look if this doesn't break the pdf generation.

**Comment by simonschllng** [comment]
As far as I remember, the div's were added by @poohsen to get tables in pdf working.

**Comment by poohsen** [comment]
yes. the rationale being that they aren't displayed on github but they can contain an HTML comment that contains the line of dashes in the right length. For the PDF generation the <div> and comment are removed and we're left with the dashes that we need to make a table in `pandoc`

**Comment by RobertdeLeeuw-IHomer** [comment]
Just tried building the PDF with these changes. Nope, tables are broken in the PDF.
So we will need a different solution.

Problem is, it used to work in GitHub, GitHub has made some changes to their system, now it doesn't work anymore...
[OCPI_2.x-TABLE.pdf](https://github.com/ocpi/ocpi/files/946347/OCPI_2.x-TABLE.pdf)

**Comment by RobertdeLeeuw-IHomer** [comment]
By adjusting the build script, not do the part that converts the markdown into the correct format needed for pandoc... I do get tables in de PDF... BUT: line wrap is not working in tables. Look for example at page 27. 

@poohsen any ideas? Do you have time to look into this?
[OCPI_2.x-TABLE.pdf](https://github.com/ocpi/ocpi/files/946367/OCPI_2.x-TABLE.pdf)

**Comment by poohsen** [comment]
Robert, can you please try PR #133 ? It's a comprehensive fix for all *.md files and I tested the PDF generation for a couple of tables (not all).

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed via a different pull request

**Pull request closed without merging**
