### PR TITLE
Update mod_tokens.md

### PR DESCRIPTION
**Pull request by goelectricstations**

### CODE REVIEW

**Comment by RobertdeLeeuw-IHomer** [comment]
Why this pull request? What are you trying to fix?

**Comment by goelectricstations** [comment]
Because are "ids" and should be array, not true?

**Comment by RobertdeLeeuw-IHomer** [comment]
The cardiology is * which means the it is an array, the type is string(39), so it is an array of strings.

**Comment by goelectricstations** [comment]
ok, but It does look so clear.  Maybe in the description scould be write also array of strings.

Thank you

**Comment by RobertdeLeeuw-IHomer** [comment]
If you think we can improve the way we document the difference between a list of a single field, I'm always open for improvement. In the current version we only use the Card. column for that. With the description: https://github.com/ocpi/ocpi/blob/master/terminology.md#cardinality

**Comment by RobertdeLeeuw-IHomer** [comment]
No response after last comment.

**Pull request closed without merging**
