### PR TITLE
Release 2.2 bugfixes

### PR DESCRIPTION
**Pull request by sc479**
When a party responds to a POST/PUT Credentials request it cannot know whether the response was processed by the other party (who originally sent the POST/PUT). This may result in the breakdown of a registration in case of an update process (retaining the old registration would be a better outcome in this case?)

### CODE REVIEW

**Comment by RobertdeLeeuw-IHomer** [comment]
@sc479, may I ask why you want to merge the bugfix branch into the master branch? Or was this not your intention?

**Comment by sc479** [comment]
Sorry, it was not my intention. How else can I suggest fixes, other than
pull requests?
I am kind of newbie to github...

regards,
h

**Comment by RobertdeLeeuw-IHomer** [comment]
@sc479, pull requests are the best solution. 

For this, you need to fork the release-2.2-bugfixes branch in you own Github account. Then make the changes, commit them to your own branch. When you are done, do a pull request to the OCPI release-2.2-bugfixes branch. 

When we release a new version of OCPI or a documentation update we will do the merge from this bugfix branch to the master branch. 

We favor contributions via pull-request as this is less work for the maintainers of OCPI. 
But if you are not familiar with OCPI, if it takes to long, you can always post an issues in Github, make clear what is wrong. We can always make the fixes.

**Comment by sc479** [comment]
Thank you for the clarification. I will post an issue then since my post is
not a bugfix per se
(rather it points out a possible defect).

**Comment by RobertdeLeeuw-IHomer** [comment]
Your welcome. 

I will close this pull request now.

**Pull request closed without merging**
