### PR TITLE
response_url purpose

### PR DESCRIPTION
**Pull request by sc479**
response_url is probably for use in CommandResult (2.2 asynchronous) instead of CommandResponse

### CODE REVIEW

**Comment by sc479** [comment]
response_url is probably for use in CommandResult (2.2 asynchronous) instead of CommandResponse

**Comment by RobertdeLeeuw-IHomer** [comment]
Good find, while look at it, I find more things wrong with this text, this is also the CancelReservation, not the 'ReserveNow'. and also the text of 'ReserveNow.response_url' contains 'CommandResponse' instead of 'CommandResult'

First, could you change the pull to correct branch? release-2.2-bugfixes
We want to keep the last release in the master branch.

Can you then make the other fixes as well? If not, I can also do them.

**Comment by sc479** [comment]
I will try, although i'm new to github.
I will let you know if i fail and give up on it :-)

regards,
h

**Comment by RobertdeLeeuw-IHomer** [comment]
Let me known, I can also make the change.

**Pull request closed without merging**
